services:
  api:
    build:
      context: .
      dockerfile: Fundo.Applications.WebApi/Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password1*"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"